# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: cb1fe6093f4f14696ff582c32c3201b00cbac0e3c5f350487db08866222f0a23434eaa2dc0e0094ec14041ef90c101a64b3df9eb06d8ca4719744fff60013796

test:
  domain_name: example.com 
  secret_key_base: 35f177d57fe4236270b0c663be65393f5375912b18fdb341e1b9d8425eafe5e78f9473b0b4ff4a45836633de3539123dd40300ed8922ce246e62522acde8f208

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
